In [10]:
%run ../talktools.py

<img src="http://dask.readthedocs.io/en/latest/_images/dask_horizontal.svg"
     align="right"
     width="30%"
     alt="Dask logo">
     
# Dask 

Dask is a parallelization library for Python that works on your laptop all the way to cluster-scale (ie. distributed multi-node)

Main focus on creating distributed array-like abstraction: Numpy- and Pandas-like behavior.

Stack:

- Array, bag, dataframe, delayed
- Graph spec
- Scheduler

Let's you focus on algorithms and not scheduling.

Tutorial: https://github.com/dask/dask-tutorial

See also some amazing new lectures/tutorials:

https://www.youtube.com/watch?v=5Md_sSsN51k&list=PLYx7XA2nY5Gf37zYZMw6OqGFRPjB1jCy6&index=17

and a shorter talk by Matt on Dask:

https://www.youtube.com/watch?v=PAGjm4BMKlk&list=PLYx7XA2nY5Gf37zYZMw6OqGFRPjB1jCy6&index=16

<div class="alert alert-info">
    IPython (via <a href="https://github.com/ipython/ipyparallel">ipyparallel</a>) also has a clustering mechanism for distribution computing. See e.g. <a href="https://ipyparallel.readthedocs.io/en/latest/examples/Monitoring%20an%20MPI%20Simulation%20-%202.html?highlight=mpi">ipyparallel with MPI</a>
</div>


In [ ]:
#!brew install graphviz ## on a mac
#!apt-get install graphviz ## on linux
#!pip install graphviz ## dont do this with conda, installs a Python 2 package...

## Dask Arrays

Distributed notion of an array. `Dask.array` translates your array operations into a graph of inter-related tasks with data dependencies between them. Dask then executes this graph in parallel with multiple threads. We'll discuss more about this in the next section.

Manipulate `dask.array` object as you would a numpy array

In [1]:
import dask.array as da
x = da.linspace(1,10,1000000,chunks=(1000,))

In [2]:
import numpy as np
y = np.linspace(1,10,1000000)
sum(y)

5500000.0

In [3]:
x.shape

(1000000,)

In [4]:
x.sum()

dask.array<sum-aggregate, shape=(), dtype=float64, chunksize=(), chunktype=numpy.ndarray>

In [5]:
rez = x.sum()

In [6]:
rez.compute()

5500000.000000018

In [7]:
import numpy as np
import dask.array as da

x = da.random.normal(10, 0.1, size=(20000, 20000),   # 400 million element array 
                              chunks=(1000, 1000))   # Cut into 1000x1000 sized chunks
y = x.mean(axis=0)[::100]                            # Perform NumPy-style operations

In [8]:
x.nbytes / 1e9  # Gigabytes of the input processed lazily

3.2

In [9]:
%%time
y.compute()     # Time to compute the result

CPU times: user 11.2 s, sys: 155 ms, total: 11.4 s
Wall time: 1.23 s


array([ 9.99956511,  9.99956771,  9.99976258,  9.99913019,  9.99994127,
        9.99964266, 10.0007248 , 10.00026324, 10.00036574, 10.00021503,
       10.00066478,  9.99981511,  9.99967292, 10.000423  , 10.00033386,
       10.00058993, 10.00094371,  9.99968657,  9.99899676,  9.99916072,
       10.00056299, 10.00067791,  9.99872484,  9.9993747 , 10.0009326 ,
       10.00015615,  9.99994366, 10.00039799, 10.00139599,  9.99928316,
       10.00028358,  9.9982434 , 10.00012764,  9.99935125,  9.99975777,
       10.00048602, 10.00034422, 10.00001139,  9.99989327,  9.99901056,
       10.00023832, 10.00011967, 10.00002729,  9.99996928,  9.99994281,
        9.99943975, 10.00000317, 10.00045913,  9.99978366, 10.0004624 ,
       10.00095599,  9.99912259,  9.99923837, 10.00045296, 10.00064786,
       10.0006476 ,  9.99955634,  9.99949006,  9.99908769,  9.99957182,
       10.00000208, 10.00063712,  9.99996717,  9.99949539,  9.99950805,
       10.00004499,  9.99993188,  9.99962345,  9.99951629, 10.00

In [10]:
import numpy as np

In [11]:
%%time 
# this will take AWHILE (~30 sec)
x = np.random.normal(10, 0.1, size=(20000, 20000)) 
y = x.mean(axis=0)[::100] 
y

CPU times: user 9.64 s, sys: 1.24 s, total: 10.9 s
Wall time: 10.9 s


array([10.000128  , 10.00010745, 10.00063502,  9.99973057,  9.99916346,
        9.99992144,  9.99923082,  9.99928607, 10.00091094,  9.99987379,
       10.00113325,  9.99964503, 10.00185312,  9.99991401, 10.00072054,
       10.00044396, 10.00139738, 10.00090671,  9.99810499, 10.00009852,
       10.00046994, 10.00011729,  9.99964628, 10.00088007, 10.00001302,
       10.00060543,  9.99857227, 10.00041957,  9.99902732, 10.00095633,
        9.99880556, 10.00054491, 10.00039454,  9.99920121,  9.99982288,
        9.99957332, 10.00102696,  9.99990399,  9.99815747,  9.99904385,
        9.99998869,  9.99934058, 10.00070466, 10.00005395, 10.00004086,
        9.99973937, 10.00079306,  9.99982625,  9.99940656,  9.99999604,
        9.99758708,  9.99982594, 10.00054597, 10.00052327,  9.99939335,
       10.00063787,  9.99940422, 10.00093075, 10.00103529,  9.99941421,
        9.99967411, 10.00025062, 10.00080704, 10.00022079, 10.00040801,
       10.00079272,  9.99855371,  9.99982699,  9.99985332,  9.99

In [12]:
del x

In [13]:
%%time
x = da.random.normal(10, 0.1, size=(20000, 20000), chunks=(1000, 1000))
y = x.mean(axis=0)[::100] 
y.compute()

CPU times: user 11.1 s, sys: 121 ms, total: 11.2 s
Wall time: 1.24 s


array([ 9.9995165 ,  9.99917067, 10.00014608, 10.00047346,  9.9995449 ,
       10.00027724, 10.00094447,  9.99949131,  9.99876829, 10.00036749,
        9.99990562, 10.00097219, 10.00083248, 10.00012412, 10.000009  ,
        9.99941469,  9.99909188,  9.99901613, 10.00020139,  9.99995123,
       10.00045656,  9.99834244,  9.99908101,  9.99900986, 10.00073077,
       10.00008423,  9.99966799, 10.00046661,  9.99919781,  9.9995831 ,
        9.99965585,  9.9998946 , 10.00056861,  9.9995468 ,  9.99982713,
       10.00076907,  9.99956   ,  9.99952729, 10.00054635,  9.99983106,
        9.99900618, 10.00021119,  9.99928124, 10.00151639, 10.00013265,
        9.99983279,  9.99963846, 10.00045739,  9.99987318, 10.00089598,
        9.99987148,  9.99981121, 10.00193164, 10.0013102 , 10.00055269,
       10.00002242, 10.0010651 , 10.00135736,  9.99894217, 10.00075295,
       10.00105562,  9.99989841, 10.00020103,  9.99924667,  9.99976078,
       10.00007068, 10.00250307, 10.00003918, 10.00065448,  9.99

## Dask Dataframes

meant to mimick most of pandas dataframes, but now these dataframes can be out of core.

In [ ]:
!ls -lah ../01_Plotting_and_Viz/data/

In [ ]:
import dask.dataframe as dd
import pandas as pd

In [ ]:
%%time
df = pd.read_csv("../01_Plotting_and_Viz/data/uber-raw-data-apr14.csv")

In [ ]:
del df

In [ ]:
%%time
df = dd.read_csv("../01_Plotting_and_Viz/data/uber-raw-data-apr14.csv")

Some of the reading in is delayed, but we can still inspect the data.

In [ ]:
df.head()

Other operations are delayed until you compute them:

In [ ]:
df.describe()

In [ ]:
df.describe().compute()

In [ ]:
df.describe()['Lat'].compute()

Let's use distributed dataframes to analyze NYC Taxi data stored as CSV files on S3.
This data is stored as large CSV files on S3 in a public bucket.

(https://github.com/mrocklin/scipy-2016-parallel/blob/master/notebooks/08-distributed-dataframes.ipynb)

In [ ]:
#!pip install s3fs

In [ ]:
from s3fs import S3FileSystem
s3 = S3FileSystem(anon=True)

s3.ls('dask-data/nyc-taxi/2015')

We would like to load this data with Pandas, but there is too much data here to fit in memory.

In [ ]:
s3.info('dask-data/nyc-taxi/2015/yellow_tripdata_2015-01.csv')

In [ ]:
import pandas as pd

with s3.open('dask-data/nyc-taxi/2015/yellow_tripdata_2015-01.csv') as f:
    df = pd.read_csv(f, nrows=5)  # look at just five rows
    
df

In [ ]:
from dask.distributed import Client, progress

e = Client(set_as_default=True)
e

In [ ]:
import dask.dataframe as dd

df = dd.read_csv('s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-01.csv',
                 parse_dates=['tpep_pickup_datetime', 'tpep_dropoff_datetime'],
                 storage_options={'anon': True})
df

In [ ]:
df = e.persist(df)
progress(df)

Existing Pandas experience transfers over decently well to Dask.dataframe. However there are a few caveats when dealing with distributed systems:
   - Until you call e.persist (for large results) or e.compute (for small results), all computations are lazy
   - Call progress on a dataframe after you persist to track the progress of a computation. You can continue doing work immediately. All work happens in the background.
   - If you are computing a small result, just add .compute() to the end of your result, like df.passenger_count.sum().compute(). This will block and return the result when finished.

In [ ]:
positive_fares = df[df.fare_amount > 0]
fares = df[['fare_amount', 'tip_amount', 'payment_type']]

fares = e.persist(fares)  # triggers computation
progress(fares)

In [ ]:
fares.head()

In [ ]:
(fares.tip_amount == 0).sum().compute()

In [ ]:
fares.count().compute()

In [ ]:
df.passenger_count.sum().compute()

Instead, we connect to the cluster and use dask.dataframe to load the CSV data into ~700 Pandas dataframes spread across our cluster. We get back a Dask.dataframe to coordinate these small Pandas dataframes.

`dask.delayed` (a la joblib):
 
   - `delayed(function)(*args, **kwargs)` -> lazy function that hasn't yet been evaluated
   - `delayed(data)` -> lazy object that pretends to be your data
 
 See the excellent talk at SciPy 2016: https://www.youtube.com/watch?v=PAGjm4BMKlk&list=PLYx7XA2nY5Gf37zYZMw6OqGFRPjB1jCy6

In [ ]:
# get a local Executor client
from distributed import Client
Client(set_as_default=True)

In [ ]:
import random
from dask import delayed, visualize
from time import sleep

@delayed(pure=True)
def add(a,b):
    sleep(random.random())
    return a+b

@delayed(pure=True)
def mul(a,b):
    sleep(random.random())
    return a*b

@delayed(pure=True)
def inc(a):
    sleep(random.random())
    return a + 1

In [ ]:
x = add(1,2)
x

In [ ]:
x.compute()

In [ ]:
a = inc(1)
b = mul(1,2)
c = add(a,b)
c

In [ ]:
c.visualize(rankdir="LR")

In [ ]:
c.compute()

### Loops

In [ ]:
results = []
for x in range(4):
    a = inc(1)
    b = mul(1,x)
    c = add(a,b)
    results.append(c)

total = delayed(sum,pure=True)(results)
total

In [ ]:
total.visualize(rankdir="LR")

`pure=True`: finds nested shared expressions deep in code that dont need to be recomputed. Eg. `inc(1)` here is the same so it only gets called once. A pure function should have no side-effects.

In [ ]:
total.compute()

In [ ]:
results = []
for y in range(2,10,2):
    for x in range(4):
        a = inc(1)
        b = mul(y,x)
        c = add(a,b)
        results.append(c)

total = delayed(sum,pure=True)(results)
total

In [ ]:
total.visualize()

In [ ]:
total.compute()

In [ ]:
# Tree reduction --- add up pairwise
while len(results) > 1:
    new_results = []
    
    for i in range(0,len(results),2):
        res = add(results[i], results[i+1])
        new_results.append(res)
    
    results = new_results

total = results[0]
total.visualize()

In [ ]:
total.compute()

Note: you cannot iterate over a delayed object and you can't use them in case statements (because we dont know how long they are until they've been computed)

In [ ]:
for x in range(inc(1)):
    print("hey!")

## scheduling the execution

where you run a certain piece of a parallel task depends on your architecture, what needs each piece has, and what the bottlenecks are in moving data between pieces.

The **single machine scheduler** is optimizes for larger-than-memory use. It uses:
  
   - Parallel CPU
   - Minimizes RAM: tries to remove intermediary tasks that aren't needed anymore
   - low overhead: 100$\mu$s per task
 

**Distributed scheduler** - tries to minimize data movement so you dont have to move data between computers unnecessarily.
 
 - distributed to schedule across many workers
 - works well with distributed datastores (HDFS)
 - asynchronous
 - data local
 
run `dask-scheduler` on the command line and then 

In [ ]:
from dask.distributed import Client, progress
e = Client(set_as_default=True)
e

# swap out concurrent.futures with a dask executor.

In [ ]:
%%writefile slowfunc.py
from time import sleep

def slowfunc(x,y,delay=1):
    sleep(delay)
    return(x+y)

In [ ]:
%%time
from slowfunc import slowfunc
futures = [e.submit(slowfunc,1,2, delay=1) for _ in range(100)]
[f.result() for f in futures]

In [ ]:
e.close()

There are loads of ways to do mapping now in Python, [this notebook](https://github.com/mrocklin/scipy-2016-parallel/blob/master/notebooks/map-rosetta-stone.ipynb) is the Rosetta stone.

<div class="alert alert-info">
   You can also use MPI with Dask...see <a href="http://mpi.dask.org/en/latest/install.html">dask_mpi</a>
</div>

<img src="https://jax.readthedocs.io/en/latest/_static/jax_logo_250px.png">

Jax is accelerated numpy (and more): https://jax.readthedocs.io/en/latest/jax-101/01-jax-basics.html

We'll see more of jax when we do ML, since it also provides automatic differentiation for us.

In [ ]:
import jax
import jax.numpy as jnp

In [ ]:
x = jnp.arange(10)
print(x)

In [ ]:
n_devices = jax.local_device_count() 
n_devices

JAX uses the XLA compiler under the hood, and enables you to just-in-time (jit) compile your code to make it faster and more efficient. This is the purpose of the @jit annotation. 

In [ ]:
from jax import numpy as jnp, random

def selu(x, alpha=1.67, lmbda=1.05):
    return lmbda * jnp.where(x > 0, x, alpha * jnp.exp(x) - alpha)

v = random.normal(random.PRNGKey(42), (1000000,))
%timeit selu(v).block_until_ready()

In [ ]:
import jax

selu_jit = jax.jit(selu)
%timeit selu_jit(v).block_until_ready()

In [ ]:
long_vector = jnp.arange(int(1e7))

%timeit jnp.dot(long_vector, long_vector).block_until_ready()

Now let's try this on a GPU and TPU in [Google Colab](https://colab.research.google.com/github/profjsb/python-seminar/blob/master/DataFiles_and_Notebooks/04_Parallelism/02_dask_and_jax.ipynb)

In [ ]:
try:
    import jax.tools.colab_tpu
    jax.tools.colab_tpu.setup_tpu()
except:
    pass

In [ ]:
long_vector = jnp.arange(int(1e7))

%timeit jnp.dot(long_vector, long_vector).block_until_ready()